#!/bin/bash
# =============================================================================
# 03-deploy-ai-foundry.sh - Terraform으로 AI Foundry 배포
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="${SCRIPT_DIR}/.."
source "${SCRIPT_DIR}/../config.env"

# SUBSCRIPTION_ID가 비어있으면 현재 구독에서 가져오기
if [ -z "$SUBSCRIPTION_ID" ]; then
    SUBSCRIPTION_ID=$(az account show --query id -o tsv 2>/dev/null)
fi

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 시간 측정 시작
START_TIME=$(date +%s)

echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE} [3/8] AI Foundry 배포 (Terraform)${NC}"
echo -e "${BLUE}=============================================${NC}"
echo -e "${YELLOW}시작 시간: $(date '+%Y-%m-%d %H:%M:%S')${NC}"

cd "$INFRA_DIR"

# -----------------------------------------------------------------------------
# Terraform 변수 파일 생성
# -----------------------------------------------------------------------------
echo -e "\n${YELLOW}Terraform 변수 파일 생성 중...${NC}"

cat > terraform.tfvars << EOF
# Auto-generated by 03-deploy-ai-foundry.sh
location            = "$LOCATION"
resource_group_name = "$RESOURCE_GROUP_NAME"
ai_services_name    = "$AI_SERVICES_NAME"
project_name        = "$PROJECT_NAME"
project_description = "$PROJECT_DESCRIPTION"
display_name        = "$DISPLAY_NAME"

# Model settings
model_name     = "$MODEL_NAME"
model_format   = "$MODEL_FORMAT"
model_version  = "$MODEL_VERSION"
model_sku_name = "$MODEL_SKU_NAME"
model_capacity = $MODEL_CAPACITY

# Tags
tags = {
  Environment = "$TAG_ENVIRONMENT"
  Project     = "$TAG_PROJECT"
  ManagedBy   = "$TAG_MANAGED_BY"
}
EOF

echo -e "${GREEN}✓ terraform.tfvars 생성됨${NC}"

# -----------------------------------------------------------------------------
# Terraform Init
# -----------------------------------------------------------------------------
echo -e "\n${YELLOW}Terraform 초기화 중...${NC}"
terraform init -upgrade
echo -e "${GREEN}✓ Terraform 초기화 완료${NC}"

# -----------------------------------------------------------------------------
# Terraform Validate
# -----------------------------------------------------------------------------
echo -e "\n${YELLOW}Terraform 구성 검증 중...${NC}"
terraform validate
echo -e "${GREEN}✓ 구성 검증 완료${NC}"

# -----------------------------------------------------------------------------
# Terraform Plan
# -----------------------------------------------------------------------------
echo -e "\n${YELLOW}Terraform Plan 실행 중...${NC}"
terraform plan -out=tfplan

# -----------------------------------------------------------------------------
# Terraform Apply
# -----------------------------------------------------------------------------
echo -e "\n${YELLOW}Terraform Apply 실행 중...${NC}"
echo -e "${YELLOW}(Capability Host 생성에 15-20분 소요될 수 있습니다)${NC}"

terraform apply -auto-approve tfplan

# 출력 저장
terraform output -json > "${SCRIPT_DIR}/../outputs.json"

# -----------------------------------------------------------------------------
# 결과 출력
# -----------------------------------------------------------------------------
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
MINUTES=$((DURATION / 60))
SECONDS=$((DURATION % 60))

echo -e "\n${BLUE}배포 결과:${NC}"
terraform output

echo -e "\n${GREEN}=============================================${NC}"
echo -e "${GREEN} [3/8] AI Foundry 배포 완료${NC}"
echo -e "${GREEN} 소요 시간: ${MINUTES}분 ${SECONDS}초${NC}"
echo -e "${GREEN}=============================================${NC}"
